drivers: touchscreen: fts_spi: Set missing functions prototypes
../../../../../../kernel/xiaomi/sm8350/drivers/input/touchscreen/fts_spi/fts_lib/ftsIO.c:104:22: error: a function declaration without a prototype is deprecated in all versions of C [-W
error,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void
../../../../../../kernel/xiaomi/sm8350/drivers/input/touchscreen/fts_spi/fts_lib/ftsIO.c:129:29: error: a function declaration without a prototype is deprecated in all versions of C [-W
error,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void
2 errors generated.

Change-Id: I2c181b61be86df10d98cdace5d42b322ac02cf7f